CREATE TABLE ML_NOTIFICACOES(
  ID INT NOT NULL PRIMARY KEY,
  ID_API VARCHAR(42),
  RESOURCE VARCHAR(1000),
  USER_ID INT,
  TOPIC VARCHAR(100),
  APPLICATION_ID VARCHAR(80),
  ATTEMPTS INT,
  SENT TIMESTAMP,
  RECEIVED TIMESTAMP,
  LIDO CHAR(1) DEFAULT 'F'
);

CREATE GENERATOR GEN_ML_NOTIFICACOES_ID;

SET GENERATOR GEN_ML_NOTIFICACOES_ID TO 0;

CREATE OR ALTER TRIGGER TRG_ML_NOTIFICACOES_ID FOR ML_NOTIFICACOES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_ML_NOTIFICACOES_ID, 1);
END;
